### PR TITLE
Remove StencilSystem._getBitwiseMask

### PR DESCRIPTION
**Pull request by dev7355608**
##### Description of change

The bit mask returned by `_getBitwiseMask` doesn't seem to make a lot of sense. Maybe it's a leftover from a previous implementation. So I removed it.

Bonus bug fix: `gl.clearStencil(0)` needs to be before `gl.clear(gl.STENCIL_BUFFER_BIT)` not after.

##### Pre-Merge Checklist

- [ ] Tests and/or benchmarks are included
- [ ] Documentation is changed or added
- [x] Lint process passed (`npm run lint`)
- [x] Tests passed (`npm run test`)

### CODE REVIEW

**Comment by ShukantPal** [comment]
Why doesn't `_getBitwiseMask` make sense? Is it unnecessarily specific?

**Comment by dev7355608** [comment]
> Why doesn't `_getBitwiseMask` make sense? Is it unnecessarily specific?

It doesn't serve any purpose at the moment. It's always large enough. It does the same thing as all the bits 1 mask. The bit mask gets one bit larger for each stencil mask on the stack; the values in the stencil buffer are just incremented/decremented though.

**Review by ShukantPal — APPROVED** [review]

**Review by GoodBoyDigital — APPROVED** [review]
yeah, this looks like it used to be when we had the super complex graphics objects (that rendered geometry using stencil buffer and triangle fan)

**Review by bigtimebuddy — APPROVED** [review]

**Comment by bigtimebuddy** [comment]
Thanks @dev7355608 for making our codebase better.

**Pull request merged**
