### PR TITLE
Fix incorrect BitmapText text width (#8432)

### PR DESCRIPTION
**Pull request by grebinka**
##### Description of change

charRenderData.position.x has already include xOffset so you should decrease xAdvance by it

##### Pre-Merge Checklist

- [x] Lint process passed (`npm run lint`)

### CODE REVIEW

**Comment by tsopeh** [comment]
I can confirm that this fix resolves [my problem](https://github.com/pixijs/pixijs/issues/8432#issuecomment-1180415626) described in #8432.

**Comment by bigtimebuddy** [comment]
@grebinka thanks for the fix. Would you mind creating a preview of this? Would be helpful to see some examples for verification.

**Comment by grebinka** [comment]
@bigtimebuddy could you give me any example of preview please? I actually don't exactly understand what it should be like.

**Comment by grebinka** [comment]
Also I don't understand why not just sum char's xAdvance whith _letterSpacing. I guess everybody expect such behavior.

**Comment by bigtimebuddy** [comment]
@grebinka Examples are the easiest way for us to understand the visual impact of this change. The implementation in the PR seems correct, but it would be helpful to have a few examples. There may be some demos you may be able to repurpose in #7479, #7933 or searching for BitmapText in issues/pull-requests.

And here's is a build you can use: https://pixijs.download/pr-8536/pixi.min.js

**Review by bigtimebuddy — APPROVED** [review]
I was able to verify examples that this fixed this jittering in the attached issue.

**Pull request merged**
