### PR TITLE
fix: strokeContains should use alignment

### PR DESCRIPTION
**Pull request by dapi303**
##### Description of change
Alignment for stroke is not used in strokeContains() methods, result of the function should vary depend on alignment.

##### Pre-Merge Checklist

- [x] Tests and/or benchmarks are included
- [x] Lint process passed (`npm run lint`)
- [x] Tests passed (`npm run test`)

### CODE REVIEW

**Comment by GoodBoyDigital** [comment]
heya! apologies for the delay on responding - this looks like a great PR. Will aim to review today.

**Comment by dapi303** [comment]
Hey,
it has conflicts after tests reorganization PR, I will try to resolve it today.

**Comment by dapi303** [comment]
ready to check

**Review by GoodBoyDigital — APPROVED** [review]
lovel PR and great test coverage! Thanks @dapi303

**Pull request merged**
