### PR TITLE
Chore: Add npm caching to GitHub Actions

### PR DESCRIPTION
**Pull request by bigtimebuddy**
Seeing if npm cache makes much of a difference

### CODE REVIEW

**Comment by vikpe** [comment]
the first run will be slower as it has to generate a cache; second run should be faster.

**Comment by bigtimebuddy** [comment]
I'll touch this again to see the delta. 

My comparison, here's a quick sample of the `npm ci` duration on Actions:

* 1:38
* 0:39
* 0:41
* 0:39
* 0:26

If we're looking at optimization opportunities, testing and building are the slowest. Maybe adding more parallelization to the build step would help speed-up.

**Comment by bigtimebuddy** [comment]
After the touch:

* 0:52
* 0:32

Seems inline with priors. Thoughts?

**Comment by vikpe** [comment]
does't seem to yield much of a difference.

**Comment by bigtimebuddy** [comment]
I think article might have some useful stuff:
https://www.rupeshtiwari.com/caching-dependencies-on-github-workflows/

**Comment by bigtimebuddy** [comment]
I'm going to close this as I don't have time to dig in. But if someone wants to try to get caching work for node_modules, that could help us save another minute or so on our CI.

**Comment by SuperSodaSea** [comment]
> It uses [actions/cache](https://github.com/actions/cache) under the hood for caching **global** packages data but requires less configuration settings.

> **Note:** The action does not cache `node_modules`

So in order to cache `node_modules` we need to use `actions/cache` manually.

**Pull request closed without merging**
