### PR TITLE
Remove duplicate lines from BitmapText's drawGlyph

### PR DESCRIPTION
**Pull request by serglider**
##### Pre-Merge Checklist

- [ ] Tests and/or benchmarks are included
- [ ] Documentation is changed or added
- [ ] Lint process passed (`npm run lint`)
- [ ] Tests passed (`npm run test`)

### CODE REVIEW

**Comment by serglider** [comment]
Guys, two test cases failed when I ran test locally saying this: [screenshot](https://i.imgur.com/QAiLisP.png)

As it's completelly unrelated to the subject, I submitted the PR anyway.

**Review by SukantPal — APPROVED** [review]
Nice catch!

**Review by bigtimebuddy — APPROVED** [review]

**Comment by bigtimebuddy** [comment]
Can you please revert the package-lock.json changes @serglider?

**Comment by bigtimebuddy** [comment]
Thanks @serglider :tada:

**Pull request merged**
