### PR TITLE
Fix spritesheetLoader to pass metadata to all loaded multipack resources (#7714)

### PR DESCRIPTION
**Pull request by Gawlas**
##### Description of change
Fix SpritesheetLoader to pass metadata to all loaded multipack resources, currently, metadata are used only to the first (parent) resource.

Related Issue: https://github.com/pixijs/pixijs/issues/7714

##### Pre-Merge Checklist

- [x] Tests and/or benchmarks are included
- [x] Lint process passed (`npm run lint`)
- [x] Tests passed (`npm run test`)

### CODE REVIEW

**Review by bigtimebuddy — APPROVED** [review]
This sounds reasonable to me :+1:

**Comment by bigtimebuddy** [comment]
Could you resolve conflicts with SpritesheetLoader?

**Review by miltoncandelero — APPROVED** [review]
LGTM

**Review by GoodBoyDigital — APPROVED** [review]

**Comment by bigtimebuddy** [comment]
Thanks @Gawlas :tada:

**Comment by Gawlas** [comment]
@bigtimebuddy sorry, I didn't have time to resolve conflicts before, I wanted to do it today and I see that you already did it, thanks!

**Comment by bigtimebuddy** [comment]
No worries, thanks for the PR.

**Pull request merged**
