### PR TITLE
Reformat Circle.ts, Ellipse.ts documentation

### PR DESCRIPTION
**Pull request by ShukantPal**
##### Description of change
#7159

### CODE REVIEW

**Comment by bigtimebuddy** [comment]
Circle and Ellipse should be in PIXI namespace.

https://pixijs.download/chore/docs-Circle-Ellipse/docs/index.html

**Comment by ShukantPal** [comment]
@bigtimebuddy Ready for review!

**Comment by bigtimebuddy** [comment]
Still not right. Needs to be memberof not namespace. Please look at the output docs now there are three PIXI entries.

**Comment by ShukantPal** [comment]
Foolish mistake from me @bigtimebuddy, fixed!

**Review by bigtimebuddy — APPROVED** [review]

**Review by Zyie — APPROVED** [review]

**Pull request merged**
