### PR TITLE
Refactor `buildNonNativeLine`

### LINKED ISSUE #9030: Bug: LINE_JOIN.ROUND fails when MiterLimit is <= 4.0
### Current Behavior

Applying LINE_JOIN.ROUND with a MiterLimit of <= 4.0 results in LINE_JOIN.BEVEL.

### Expected Behavior

LINE_JOIN.ROUND to be applied.

### Steps to Reproduce

https://www.pixiplayground.com/#/edit/SMsc63jIec6ge6m5bhrlF

### Environment

- **`pixi.js` version**: *e.g. 7.1.0*
- **Browser & Version**: *e.g. Chrome 108*
- **OS & Version**: *e.g. Ubuntu 22.04*
- **Running Example**: *e.g. <https://pixiplayground.com/>*

### Possible Solution

It appears removing `|| pdist / widthSquared > miterLimitSquared` from the `buildNonNativeLine` method resolves this issue, however, I'm not confident removing this won't result in other unexpected issues. @ShukantPal might know the answer to this?

### PR DESCRIPTION
**Pull request by SuperSodaSea**
#### Description of change

- Fixes #9030
- Merge adjacent `Arrays.push`

#### Tests

- Before: <https://pixiplayground.com/#/edit/3aOjK1Uk2b-RJp24rarS0>
- After: <https://pixiplayground.com/#/edit/cgHPnSJF5mzFyQu4l7aOz>

And tests from previous PRs still works fine:

- From #8325: <https://www.pixiplayground.com/#/edit/JYmY8a_KvmM48jTseA-ON>
- From #8771: <https://pixiplayground.com/#/edit/SJE2J37778M9Px1EYzBGL>

#### Pre-Merge Checklist

- [x] Tests and/or benchmarks are included
- [x] Lint process passed (`npm run lint`)
- [x] Tests passed (`npm run test`)

### CODE REVIEW

**Comment by bigtimebuddy** [comment]
Could you provide links to some previews from former issues related to this? Want to make sure we don't have any regressions as this code is complicated and has lots of edge cases.

**Comment by SuperSodaSea** [comment]
> Could you provide links to some previews from former issues related to this? Want to make sure we don't have any regressions as this code is complicated and has lots of edge cases.

Work in progress!

**Comment by bigtimebuddy** [comment]
Thanks for taking this on!

**Review by bigtimebuddy — APPROVED** [review]
Great work 👍

**Pull request merged**
