### PR TITLE
Chore: Upgrade to TypeScript 4.3.0 and make setters for ObservablePoints accept IPointData

### LINKED ISSUE #8258: why does TilingSprite expect an ObservablePoint as tilingScale?
### Expected Behavior

The tilingScale attribute of the TilingSprite class expects an ObservablePoint only to cast it to the IPoint interface. I think it should already require only the the IPoint interface at the first place:

```
set tileScale(value: IPoint)
{
    this.tileTransform.scale.copyFrom(value);
}
```

### Current Behavior
```
set tileScale(value: ObservablePoint)
{
    this.tileTransform.scale.copyFrom(value as IPoint);
}
``

### Environment

- **`pixi.js` version**:  master and latest release 6.3.0
- **typescript**: "^4.6.3"

### PR DESCRIPTION
**Pull request by ShukantPal**
Fixes #8258

### CODE REVIEW

**Comment by ShukantPal** [comment]
Do not merge this yet − TypeScript 4.5.5 analysis is failing @microsoft/api-extractor from generating the type definition files.

**Comment by ShukantPal** [comment]
Fixed by downgrading to @microsoft/api-extractor ~7.20.1

**Review by bigtimebuddy — APPROVED** [review]
Awesome fix, about time

**Comment by bigtimebuddy** [comment]
Thanks @ShukantPal

**Pull request merged**
