### PR TITLE
fix: AnimatedSprite's `update()` logic, add support for duration-based spritesheets, fix looping functionality, and other behavior.

### PR DESCRIPTION
**Pull request by momer**
##### Description of change
This PR fixes a number of issues with `AnimatedSprite` - some of which are documented in #11033 :

- The looping functionality didn't work as expected (rather than repeating or stopping repeating animation, it abruptly stopped at frame 0).
- The looping functionality assumed loops to start at 0, and would ignore other initial animation starting frames.
- The `durations` functionality was `private` (unavailable), and the logic was both untested and incorrect.
- Loop counting and tracking - generally - was inconsistent with respect to time, and incorrect in scenarios with negative `animationSpeed`.
- Debugging or hooking into the `update()` function wasn't possible; adding in an optional hook makes maintaining and hooking in to track/log sequences in tests a lot easier (`onTickUpdate` added)
- A number of tests which relied on careful selection of configuration were brittle and failed for a number of edge cases; and they have been made a bit more robust.

Users of `AnimatedSprite` **may** notice these changes:

- If they relied on the incorrect implementation of `loop = false` and relied on the `gotoAndStop(0)` side-effect to both stop looping immediately and reset to frame 0. 
   - As the documentation states, and would be expected, setting `loop = false` indicates the desire to *not repeat*, but to finish an active animation. This, in many cases (although probably a rare use-case), should improve functionality by preventing abrupt animation frame changes (from say, frame 15 of 30 to 0, as in the linked issue).
- It's possible that some usage depended on the incorrect loop and frame update behavior. Now, as should happen, after a loop, the `currentFrame` is set to the next frame to run; whereas the conditional logic within `update()` resulted in inconsistent behavior previously.

##### Pre-Merge Checklist

- [x] Tests and/or benchmarks are included
- [x] Documentation is changed or added
- [x] Lint process passed (`npm run lint`)
- [x] Tests passed (`npm run test`)
   - `AnimatedSprite` tests pass!

### CODE REVIEW

**Comment by momer** [comment]
Hey @bigtimebuddy - one of the tests in `AnimatedSprite.test.ts` appears to be flaky *only* when `npm run test:unit` or `npm run test` is run (with all other tests).

Outside of that, this is ready for review, and I'll take it out of draft mode!

When running the `AnimatedSprite.test.ts` suite by itself, it's actually not flaky. It doesn't look like it's timing out, but I would appreciate any ideas on what's causing the issue. For whatever reason, I'm unable to run any of the tests through VS Code / Webstorm, which would help debug via attaching to breakpoints :(

```shell
 FAIL  tests/renderering/animation/AnimatedSprite.test.ts
  ● Test suite failed to run

      ● AnimatedSprite › .gotoAndPlay() › should fire frame after start frame during one play and fire onComplete

        expect(received).toEqual(expected) // deep equality

        Expected: ArrayContaining [1, 2]
        Received: [1]

          201 |                     if (sprite !== null)
          202 |                     {
        > 203 |                         frameChangeSequence.push(frame);
              |                                  ^
          204 |                     }
          205 |                 });
          206 |                 sprite.onComplete = () =>

      at AnimatedSprite.sprite.onComplete (tests/renderering/animation/AnimatedSprite.test.ts:203:34)
      at AnimatedSprite.update (src/scene/sprite-animated/AnimatedSprite.ts:330:22)
      at TickerListener.emit (src/ticker/TickerListener.ts:47:26)
      at Ticker.update (src/ticker/Ticker.ts:326:37)
      at Ticker._tick (src/ticker/Ticker.ts:101:22)
```

**Comment by momer** [comment]
I've isolated the flaky test's issue to be down to, well, being a flaky test: if `jest` is running slowly, and the number of frames calculated by `elapsed = animationSpeed * deltaTime` ([ref](https://github.com/pixijs/pixijs/blob/954ce5a1ff91bcdc71232424cce3eb5afc4ff27a/src/scene/sprite-animated/AnimatedSprite.ts#L513)) will cause the animation to skip right past those frames.

In one local run, the `ticker.elapsedMS` exceeded 1000ms, which caused the `ticker.deltaMS` to hit its cap default of 100ms, leaving `ticker.deltaTime` at 6. 

`elapsed = 0.5 * 6` filling in the variables from above, which sets the new frame (in this particular example run) to `4 % 3 === 1` ([ref](https://github.com/pixijs/pixijs/blob/954ce5a1ff91bcdc71232424cce3eb5afc4ff27a/src/scene/sprite-animated/AnimatedSprite.ts#L522)).

Switching this test to `autoUpdate=false` and ticking it manually should resolve it, while preserving the test.

**Comment by momer** [comment]
Just a thought from this morning: it might be helpful to emulate the current functionality without breaking use cases like negative `animationSpeed`, by having an optional `loopTo?: number` parameter to `AnimatedSprite#.play`. This would support potential current usage patterns of "hey, we're on frame 5/30, but we want to stop looping at 0" without breaking the new supported functionality of, "actually, we want to do a complete loop from 5/30 back to 5/30".

Thoughts @bigtimebuddy ?

**Comment by Zyie** [comment]
Hey @momer 

Thank you for putting this PR together! This PR touches on several areas, including bug fixes, new features, and potential breaking changes. While we appreciate the effort, tackling so many things at once makes it challenging for us to properly review and integrate the changes.

Additionally, the class in question has not seen a meaningful update in years, and, frankly, no one on the core team fully understands its nuances anymore. This adds to the complexity of addressing such a large scope in one PR.

To keep things manageable, we’d like to ask for this PR to be split into smaller, focused changes. Specifically, we suggest starting with a PR that only addresses bug fixes without introducing breaking changes.

Alternatively, if you’re passionate about supporting this functionality, we recommend creating a separate repo (e.g., "MovieClip") where this can evolve independently. Once the new implementation has matured and proven itself, we’d be happy to discuss integrating it back into the library while deprecating `AnimatedSprite`. We have recently set up a new Github organization, [PixiJS Userland](https://github.com/pixijs-userland), where community-driven projects like this can live and grow.

Let us know how you'd like to proceed! Thank you again for your hard work and contributions.

**Comment by momer** [comment]
Following up here for anyone who stumbles along; I'm working on packaging up this implementation of `AnimatedSprite`, and will put some docs and comparisons with the current implementation together soon!

- https://github.com/momer/pixi-super-animated-sprite
- on NPM at [@momer/pixi-super-animated-sprite](https://www.npmjs.com/package/@momer/pixi-super-animated-sprite)

**Pull request closed without merging**
