### PR TITLE
Fix use of deprecated calls

### LINKED ISSUE #9069: Bug: `FILTER_MULTISAMPLE` deprecation warning triggered in MaskData
### Current Behavior

Ever since updated to v7.1, I get a console warning saying that `FILTER_MULTISAMPLE` is deprecated. This is not triggered by my code, however, but by `MaskData` in @pixi/core itself:

https://github.com/pixijs/pixijs/blob/e22f5ea2f43fd48c443b683cad15422cdba11446/packages/core/src/mask/MaskData.ts#L125

### Expected Behavior

Pixi should not use deprecated syntax itself.

### Steps to Reproduce

Since the problematic code is in `MaskData`, I suppose any pixi app using masks will reproduce it.

### Environment

- **`pixi.js` version**: 7.1.0
- **Browser & Version**: Chrome 108
- **OS & Version**: Win 11

### Possible Solution

Perform a keyword search for `FILTER_MULTISAMPLE` and other deprecated things in the code base and change them all.

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by Zyie**
Fixes #9069

### CODE REVIEW

**Review by bigtimebuddy — APPROVED** [review]

**Comment by bigtimebuddy** [comment]
Nice, thank you!

**Comment by bigtimebuddy** [comment]
@SuperSodaSea could you add any other missing ones into this PR?

**Comment by bigtimebuddy** [comment]
Yeah, those are missing @Zyie from the global.d.ts in core

**Review by SuperSodaSea — APPROVED** [review]

**Comment by bigtimebuddy** [comment]
Thank you both!

**Pull request merged**
