### PR TITLE
Fix nested interaction

### LINKED ISSUE #9299: Bug: Some mouse events not triggered in certain situations Pixi 7.2.3
### Current Behavior

After migrating from PIXI 7.1.1 to 7.2.3 some of my buttons do not work anymore.

What I have is a Container that receives all the listeners also where I set 
`container.cursor = "pointer";
  container.eventMode = "dynamic";`
Then I add a spine animation as child of this container. The button click works but mouse over and mouse out won't.

### Expected Behavior

All the button listeners including mouse over and mouse out work correctly.

### Steps to Reproduce

You can reproduce the issue here https://codesandbox.io/s/blissful-benji-fjsf70

### Environment

- **`pixi.js` version**: *7.2.3*
- **Browser & Version**: *Chrome Version 111.*
- **OS & Version**: * MacOS 13.2.1*

### Possible Solution

_No response_

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by Zyie**
Fixes #9299 #9274

[before](https://codesandbox.io/s/pixi-interaction-fix-2f8hj1?file=/src/index.js)
[after](https://github.com/pixijs/pixijs/pull/9301#issuecomment-1485321335)

also fixes nested mask interactions
https://codesandbox.io/s/pixi-interaction-masked-fix-gpjv53?file=/src/index.js

### CODE REVIEW

**Comment by SuperSodaSea** [comment]
Seems that CodeSandbox will ramdomly fail to deploy some packages :( Due to the large number of packages we have, the probability of failure will be higher.

<https://github.com/pixijs/pixijs/pull/9279#issuecomment-1476753443>

**Comment by tonywei92** [comment]
Hi, could you guys please help merge this, our team really need the fix :(

**Comment by bigtimebuddy** [comment]
@Zyie what's the status on this?

**Comment by Zyie** [comment]
@bigtimebuddy found an issue with masks and nested elements

https://codesandbox.io/s/pixi-interaction-masked-fix-gpjv53?file=/src/index.js

just need to fix this and then we are good

**Comment by Zyie** [comment]
@bigtimebuddy everything seems to be fixed now!

**Review by bigtimebuddy — APPROVED** [review]

**Comment by tonywei92** [comment]
@Zyie @bigtimebuddy Thanks, guys!
I wonder when we can expect the v7.2.4 release? thanks!!

**Comment by bigtimebuddy** [comment]
@tonywei92 will make a release today

**Pull request merged**
