### PR TITLE
fix: create instructionSet parameter from addToBatch

### PR DESCRIPTION
**Pull request by dev7355608**
##### Description of change

The `addToBatch` method of `BatchPipe` interface requires the instruction set being passed.

##### Pre-Merge Checklist

- [ ] Tests and/or benchmarks are included
- [ ] Documentation is changed or added
- [ ] Lint process passed (`npm run lint`)
- [ ] Tests passed (`npm run test`)

### CODE REVIEW

**Review by GoodBoyDigital — COMMENTED** [review]
thanks for this! Question - I wander if instead of this route, we modify the interface to not require instructionSet?

**Comment by dev7355608** [comment]
Yeah, perhaps not necessary to pass `instructionSet`. If you really needed the `instructionSet`, you could remember it in `buildStart`: `this._activeInstructionSet = instructionSet`. But if this is done, we wouldn't really need to pass `instructionSet` to `break` and `buildEnd` either technically, I suppose.

**Comment by GoodBoyDigital** [comment]
agreed! Currently, I can't see why `addToBatch` would need the instruction set so lets remove it from the interface for now. We can always change if it turns out i'm wrong :D

**Review by GoodBoyDigital — APPROVED** [review]
awesome work as usual! thanks @dev7355608

**Pull request merged**
