### PR TITLE
Feat: INT attribute format for WebGL2

### PR DESCRIPTION
**Pull request by ivanpopelyshev**
THE DEMO: https://codesandbox.io/p/sandbox/pixi-js-sandbox-forked-yvfqyj

Without provoking_vertex this can be slow. Luckily, chromium and others integrated it for a year already.

### CODE REVIEW

**Comment by GoodBoyDigital** [comment]
Heya! the demo is not working for me - its asking for a lot of github permissions! haha

**Comment by ivanpopelyshev** [comment]
Demo has been fixed. Btw, I dont expose extension because there's actually nothing there, and its appearance doesnt give any information to developer.

**Review by GoodBoyDigital — APPROVED** [review]
lgtm!

will WebGPU side of things just work? thanks!

**Comment by ivanpopelyshev** [comment]
> lgtm!
> 
> will WebGPU side of things just work? thanks!

yes, i modified webgpu shader , and set "webgpu" by default - it works

**Pull request merged**
