### PR TITLE
Fix PolygonUtils.isPolygonClockwise

### PR DESCRIPTION
**Pull request by dev7355608**
##### Description of change

`isPolygonClockwise` is missing an edge: https://www.pixiplayground.com/#/edit/vKE4GK33ISNEjLvGz9xwX

##### Pre-Merge Checklist

- [x] Tests and/or benchmarks are included
- [x] Lint process passed (`npm run lint`)
- [x] Tests passed (`npm run test`)

### CODE REVIEW

**Comment by bigtimebuddy** [comment]
Any tests you could add for this?

**Comment by dev7355608** [comment]
I just noticed that there's also a identical `isPolygonClockwise` in the `canvas-graphics` package. Fixed it as well.

**Review by bigtimebuddy — APPROVED** [review]

**Comment by dev7355608** [comment]
We can actually remove the `isPolygonClockwise` in the `graphics` package, because we don't need it anymore once #8225 is merged.

**Comment by bigtimebuddy** [comment]
Could you make a PR to remove that?

**Comment by dev7355608** [comment]
New PR, or should I remove the change to `isClockwisePolygon` in this PR, and include the removal in #8225?

**Comment by bigtimebuddy** [comment]
Preference to combine, these Graphics PRs are related and small

**Pull request merged**
