### PR TITLE
Upgrade to webdoc 1.5.4 to fix getter-setter data-type inference

### PR DESCRIPTION
**Pull request by ShukantPal**
##### Description of change
#7804, #7806 need this upgrade to strip out member tags from getter/setter properties.

* https://github.com/webdoc-labs/webdoc/pull/137
* https://github.com/webdoc-labs/webdoc/issues/136

### CODE REVIEW

**Review by bigtimebuddy — APPROVED** [review]

**Review by bigtimebuddy — CHANGES_REQUESTED** [review]
Template  dep needs to be updated here too. Currently its still ^1.3.3 and source links are still broken.

**Comment by ShukantPal** [comment]
@bigtimebuddy there's another pr to fix source links that upgrades the template

**Comment by bigtimebuddy** [comment]
Where is that PR?

**Comment by ShukantPal** [comment]
@bigtimebuddy It was #7801. I closed that due to a misreading on my part.

**Review by bigtimebuddy — APPROVED** [review]

**Review by Zyie — APPROVED** [review]

**Pull request merged**
