### PR TITLE
Add public `Framebuffer.depth` and `Framebuffer.stencil` properties

### PR DESCRIPTION
**Pull request by dev7355608**
##### Description of change

I thought it might be useful if these properties are publicly accessible and can be changed with the framebuffer automatically updating.

##### Pre-Merge Checklist

- [ ] Tests and/or benchmarks are included
- [x] Documentation is changed or added
- [x] Lint process passed (`npm run lint`)
- [x] Tests passed (`npm run test`)

### CODE REVIEW

**Comment by GoodBoyDigital** [comment]
Hey @dev7355608 ! This is certainly a technically correct PR, but i can't think of a use case where this would be useful :D
We would prefer users to make separate FB's rather than changing these on the fly I think?

**Comment by dev7355608** [comment]
Yeah, probably unlikely that these properties are changed, but I thought why not: it can't really hurt to have it.

**Comment by talented634** [comment]
Nice

**Comment by talented634** [comment]
Nice

**Comment by Zyie** [comment]
Hey,

Thank you for putting together this PR! Since we've moved to the next major version of the library, we're closing this to focus on the updated codebase. If this is still relevant, feel free to submit a new PR for the latest version.

**Pull request closed without merging**
