### PR TITLE
Add option for custom sprite mask filters

### PR DESCRIPTION
**Pull request by dev7355608**
##### Description of change

I created the option for custom sprite mask filters in order to allow any kind of masking textures and logic. I added the `filter` property to `MaskData` where the user can specify a custom filter to be used in the mask system.

Potentially problematic: a custom filter instance should not be set in multiple mask data with different sprites; if the objects are nested the `maskSprite` property would be overridden by the second push.

I also fixed a potential memory leak: the mask system's sprite mask filters never released the reference to the sprite in `popSpriteMask`.

##### Pre-Merge Checklist

- [x] Tests and/or benchmarks are included
- [x] Documentation is changed or added
- [x] Lint process passed (`npm run lint`)
- [x] Tests passed (`npm run test`)

### CODE REVIEW

**Comment by bigtimebuddy** [comment]
Could you provide a demo of this work?

**Comment by ivanpopelyshev** [comment]
I need something like that because i already have custom masks for pixi-projection  and pixi-picture. I'll look at it later )

**Comment by dev7355608** [comment]
Demo: https://sprite-mask-filter.dev7355608.repl.co/

**Comment by dev7355608** [comment]
The filter in `MaskData` is now stored wrapped in an array so that we can use it in `pushSpriteMask` and avoid repeated array creation there.

> Potentially problematic: a custom filter instance should not be set in multiple mask data with different sprites; if the objects are nested the `maskSprite` property would be overridden by the second push.

Fixed that by restoring the sprite of the current sprite mask filter in `MaskSystem.pop`. Added a test for this scenario as well.

**Comment by dev7355608** [comment]
The mask system respects the enabled property of the custom filter now.

**Comment by dev7355608** [comment]
If `enabled` is added to `MaskData`, should we respect the custom filter's `enabled` state? We don't do it for `resolution`/`multisample` and use whatever `MaskData` specifies. Maybe we should revert that last commit for consistency.

**Comment by ivanpopelyshev** [comment]
Yes, revert it and i'll approve it

**Review by ivanpopelyshev — APPROVED** [review]

**Review by GoodBoyDigital — APPROVED** [review]

**Comment by bigtimebuddy** [comment]
@dev7355608 could you resolve these conflicts?

**Comment by dev7355608** [comment]
> @dev7355608 could you resolve these conflicts?

Done!

**Pull request merged**
