### PR TITLE
check `domElement` is connected to (shadow)DOM when `mapPositionToPoint`

### PR DESCRIPTION
**Pull request by naramdash**
related issue #9291 

##### Description of change

- check `domElement` is connected to (shadow)DOM when `mapPositionToPoint` with polyfill.

The previous code judged a situation(parentElement not exists) in which the client browser was IE11 through this result.

But, a parentElement of very first child of shadowRoot is null.

So, Using isConnected api to verify that it is included in the document regardless of dom or shadow DOM.

For IE11, polyfill code is added.

##### Pre-Merge Checklist

- [x] Tests and/or benchmarks are included
- [x] Lint process passed (`npm run lint`)
- [x] Tests passed (`npm run test`)

### CODE REVIEW

**Comment by naramdash** [comment]
All tests that check function calls fail.

However, this is because the canvas used in the test code is used without a parent element,
So it seems that they all use the rect value corresponding to the IE11 fix.

And during testing, it seems that all calls to the dom element's getBoundingClientRect method fail.

**Comment by naramdash** [comment]
I changed codes related with setting styles of shadowRoot host to avoid type error that TS 4.2 doesn't support `ShadowRoot.adoptedStylesheets`.

then, i ran 
- npm run lint
- npm run test
- npm run build && npm run build:types
- npm run dist

**Comment by Zyie** [comment]
Hey @naramdash 

Pixi doesn't support IE11 anymore, so you can update this PR to remove any IE11 workarounds

**Comment by naramdash** [comment]
@Zyie 

Ok, I removed polyfill codes. and become shorter and performant :)

**Review by Zyie — APPROVED** [review]

**Comment by bigtimebuddy** [comment]
Thank you @naramdash :tada:

**Pull request merged**
