### PR TITLE
Fix GeometrySystem.getSignature

### PR DESCRIPTION
**Pull request by dev7355608**
##### Description of change

The signature currently does not include something very essential: the location where the attribute is bound. So two different VAOs can end up with the same signature, which can end very badly. For example, two shader with two attributes in different locations:

```glsl
// signature: g-XXX-aAttribute1-aAttribute2

layout(location = 0) in vec2 aAttribute1;
layout(location = 1) in vec3 aAttribute2;
```
```glsl
// same signature: incompatible VAO is used, does not render correctly

layout(location = 1) in vec2 aAttribute1;
layout(location = 0) in vec3 aAttribute2;
```

Also when the shader-geometry compatibility check is disabled (#7826), and, for example, a geometry with only one attribute `aAttributeB` is used, this example can fail as well:

```glsl
// signature: g-XXX-aAttributeB

attribute vec2 aAttributeA; // location 0, because "aAttributeA" < "aAttributeB"
attribute vec3 aAttributeB; // location 1
```
```glsl
// the signature is the same as above, but that VAO has aAttributeB is in location 1 and is incompatible

attribute vec3 aAttributeB; // location 0
```

##### Pre-Merge Checklist

- [x] Tests and/or benchmarks are included
- [x] Lint process passed (`npm run lint`)
- [x] Tests passed (`npm run test`)

### CODE REVIEW

**Review by ivanpopelyshev — APPROVED** [review]

**Review by ShukantPal — CHANGES_REQUESTED** [review]
Can you add a unit test based on the example you provide in the PR's description?

**Comment by dev7355608** [comment]
> Can you add a unit test based on the example you provide in the PR's description?

I cannot add a unit test right now that would fail, because the first example needs #7828 to be merged first, and the second example requires `GeometrySystem.checkCompatibility` to be removed first (#7826).

I made a change to the second example, because it was technically not a case where it would fail: attributes are bound in lexicographical ascending order at the moment and didn't choose the attribute names correctly when I was writing the example.

**Comment by dev7355608** [comment]
Added the unit tests.

**Review by Pi-Bouf — APPROVED** [review]

**Review by GoodBoyDigital — APPROVED** [review]
👍

**Review by bigtimebuddy — APPROVED** [review]

**Comment by bigtimebuddy** [comment]
Fixes #7976

**Pull request merged**
