### PR TITLE
Move texture.valid check

### PR DESCRIPTION
**Pull request by owendwyer**
##### Description of change
Move
`if (!texture.valid) return; `
so that it comes before the call to 
`texture._frame.width `

This prevents a crash when destroying the texture of a sprite currently being rendered.

##### Pre-Merge Checklist

- [ ] Tests and/or benchmarks are included
- [ ] Documentation is changed or added
- [x] Lint process passed (`npm run lint`)
- [x] Tests passed (`npm run test`)

### CODE REVIEW

**Comment by bigtimebuddy** [comment]
Seems reasonable. Do you think you could add a unit-test for this change?

**Review by ivanpopelyshev — APPROVED** [review]

**Comment by ivanpopelyshev** [comment]
So, after this, we have invariant "sprite texture can be destroyed, sprite just wont show anything". This thing was born because somehow WebGL implementation allows it. I thought that it doesnt :)

**Comment by owendwyer** [comment]
Hope this test is okay.  And thanks a lot!

**Review by bigtimebuddy — APPROVED** [review]

**Comment by bigtimebuddy** [comment]
Thanks @owendwyer :tada:

**Pull request merged**
