### PR TITLE
Fix LoaderResource tests

### LINKED ISSUE #7949: LoaderResource Tests are Failing
Because the LoaderResource test suite file was named incorrectly (`LoaderResource.test.ts` vs `LoaderResource.tests.ts`), this was masking underlying test failures.

https://github.com/pixijs/pixijs/tree/fix-loader-tests
https://github.com/pixijs/pixijs/runs/4096194238

Reproduce locally by running `npm run unit-test:debug -- --package=@pixi/loaders`

```
1) @pixi/loaders
   LoaderResource
     should construct properly with only a URL passed:
 AssertionError: expected { Object (_dequeue, _onLoadBinding, ...) } to have a property 'loadType' of 1, but got 2
  at Context.<anonymous> (/home/runner/work/pixijs/pixijs/packages/loaders/test/LoaderResource.tests.ts:44:29)

2) @pixi/loaders
   LoaderResource
     #abort
       should abort in-flight XHR requests:
 TypeError: Cannot set property 'abort' of null
  at Context.<anonymous> (/home/runner/work/pixijs/pixijs/packages/loaders/test/LoaderResource.tests.ts:140:26)
  at processImmediate (internal/timers.js:461:21)

3) @pixi/loaders
   LoaderResource
     #load
       should emit the start event:
 AssertionError: expected null to exist
  at Context.<anonymous> (/home/runner/work/pixijs/pixijs/packages/loaders/test/LoaderResource.tests.ts:196:31)
  at processImmediate (internal/timers.js:461:21)

4) @pixi/loaders
   LoaderResource
     #load
       should emit the complete event:
 TypeError: Cannot read property 'respond' of null
  at Context.<anonymous> (/home/runner/work/pixijs/pixijs/packages/loaders/test/LoaderResource.tests.ts:208:21)
  at processImmediate (internal/timers.js:461:21)

5) @pixi/loaders
   LoaderResource
     #load
       should load using XHR:
 AssertionError: expected null to exist
  at Context.<anonymous> (/home/runner/work/pixijs/pixijs/packages/loaders/test/LoaderResource.tests.ts:280:31)
  at processImmediate (internal/timers.js:461:21)
```

### PR DESCRIPTION
**Pull request by ShukantPal**
Fixes #7949 

##### Description of change

Rename LoaderResource.test.ts → LoaderResource.test**s**.ts; patch the tests that were resulting in errors because they falsely assumed they were testing XHR payloads when the fixture data was an image.

### CODE REVIEW

**Review by bigtimebuddy — APPROVED** [review]

**Comment by ShukantPal** [comment]
It's related to the fake timers @bigtimebuddy. The latest commit seemed to fix it for me locally, can you try?

**Comment by bigtimebuddy** [comment]
I'm also able to reproduce these failures locally.

```
  1) @pixi/sprite-animated
       AnimatedSprite
         .onComplete()
           should fire onComplete:
     Error: Timeout of 130ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (~/GitHub/pixijs/pixijs/test/index.ts)
  

  2) @pixi/sprite-animated
       AnimatedSprite
         .onComplete()
           should the current texture be the last item in textures:
     Error: Timeout of 2000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (~/GitHub/pixijs/pixijs/test/index.ts)
  

  3) @pixi/sprite-animated
       AnimatedSprite
         .gotoAndPlay()
           should fire frame after start frame during one play and fire onComplete:
     Error: Timeout of 2000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (~/GitHub/pixijs/pixijs/test/index.ts)
  

  4) @pixi/sprite-animated
       AnimatedSprite
         .onFrameChange()
           should fire every frame(except current) during one play:
     Error: Timeout of 2000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (~/GitHub/pixijs/pixijs/test/index.ts)
  

  5) @pixi/sprite-animated
       AnimatedSprite
         .onFrameChange()
           should fire every frame(except current) during one play - reverse:
     Error: Timeout of 2000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (~/GitHub/pixijs/pixijs/test/index.ts)
  

  6) @pixi/sprite-animated
       AnimatedSprite
         .onFrameChange()
           should fire every frame(except current) during one play - from not start/end:
     Error: Timeout of 2000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (~/GitHub/pixijs/pixijs/test/index.ts)
  

  7) @pixi/sprite-animated
       AnimatedSprite
         .textures
           should set the first frame when setting new textures:
     Error: Timeout of 2000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (~/GitHub/pixijs/pixijs/test/index.ts)
  

  8) @pixi/prepare
       BasePrepare
         should attach to the system ticker:
     Error: Timeout of 2000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (~/GitHub/pixijs/pixijs/test/index.ts)
  
```

**Comment by bigtimebuddy** [comment]
Removing the clock/fakeTimers all together fixed all but one test

**Comment by bigtimebuddy** [comment]
@Zyie could you look at this?

**Pull request closed without merging**
