### PR TITLE
Event emitter types improvements

### PR DESCRIPTION
**Pull request by zOadT**
##### Description of change

Hello,

these are just very minor changes to slightly improve DX:

1. Use labeled tuples
    * A very minor improvement in DX:
Bildschirm­foto 2022-11-06 um 09 51 35
    Before the signature of fn was `fn: (args_0: PIXI.FederatedPointerEvent) => void`
    * The syntax used requires TypeScript 4.1. If that's a problem I can replace it by just writing out the events by hand.

    
2. Add types for `*capture` events
    * These seemed to be missing, I hope this wasn't intentional?

**Note**: The event `removedFrom` doesn't seem to be used anywhere (haven't found it in the docs and neither anywhere in the code). Shall I remove this from the types?

##### Pre-Merge Checklist

- [ ] Tests and/or benchmarks are included
- [ ] Documentation is changed or added
- [ ] Lint process passed (`npm run lint`)
- [ ] Tests passed (`npm run test`)

### CODE REVIEW

**Comment by bigtimebuddy** [comment]
I think you should remove `removedFrom`. I'm not seeing any references to that either. I believe it was added in #7718. @s-r-x, any thoughts on that? Was that added by mistake?

**Review by bigtimebuddy — APPROVED** [review]
These are nice type improvements. Thank you!

**Comment by SuperSodaSea** [comment]
> I think you should remove `removedFrom`. I'm not seeing any references to that either. I believe it was added in #7718. @s-r-x, any thoughts on that? Was that added by mistake?

`removedFrom` seems to be the wrong name for `childRemoved`, which is fixed in #8582.

**Comment by zOadT** [comment]
Thank you for the clarification!

**Review by SuperSodaSea — APPROVED** [review]
LGTM!

**Comment by bigtimebuddy** [comment]
Thank you @zOadT!

**Pull request merged**
