### PR TITLE
Support loading font assets in data URLs

### LINKED ISSUE #8891: Support for loading fonts in base64 format
Hello. There is not enough support for loading a font from base64. I know that this feature has already been added for images. [https://github.com/pixijs/pixijs/pull/8559](https://github.com/pixijs/pixijs/pull/8559)
const texture = await PIXI.Assets.load('"data:font/woff2;base64,d09GMgA.......');

### PR DESCRIPTION
**Pull request by SuperSodaSea**
Support loading font assets in data URLs.

Closes #8891.

#### Description of Change

- `loadWebFont` now support data URLs
    - Valid MIME types are `font/ttf`,` font/otf`, `font/woff`, `font/woff2`
- `packages/assets/src/loader/parsers/textures/utils/index.ts` is moved to `packages/assets/src/utils/checkExtension.ts`
- `packages/assets/src/utils/checkDataUrl.ts` is added to check if a URL is a data URL with the given MIME types
- :fire: **Breaking Change**: `image/jpg` is no longer considered as a valid MIME type for `loadTextures` (only `image/jpeg` should be valid)

#### Pre-Merge Checklist

- [x] Tests and/or benchmarks are included
- [x] Lint process passed (`npm run lint`)
- [x] Tests passed (`npm run test`)

### CODE REVIEW

**Comment by bigtimebuddy** [comment]
Awesome! Can you add a test for loading a font from data-uri?

**Comment by SuperSodaSea** [comment]
Let me see if I can find a small font file for test...

**Comment by bigtimebuddy** [comment]
icomoon.io is a good place to make a font with a single glyph

**Comment by SuperSodaSea** [comment]
Test added!

**Review by bigtimebuddy — APPROVED** [review]

**Comment by bigtimebuddy** [comment]
Nice work!

**Comment by ManHunterGroms** [comment]
@SuperSodaSea thank u so much!!! Nice work 👍

**Comment by pleek91** [comment]
Is there any documentation for this? I'm unable to get this working. No errors, just a weird asset cached and Pixi.Text uses the standard serif font when rendering my text.

**Pull request merged**
