### PR TITLE
Firing a pointertap after click or tap

### PR DESCRIPTION
**Pull request by miltoncandelero**
##### Description of change
Forcing a `pointertap` to be fired after click or tap events (or any other pointing device input)

solves #8429 

##### Pre-Merge Checklist

- [x] Lint process passed (`npm run lint`)
- [x] Tests passed (`npm run test`)

### CODE REVIEW

**Review by bigtimebuddy — APPROVED** [review]
LGTM

**Comment by bigtimebuddy** [comment]
@ShukantPal any concerns?

**Comment by ShukantPal** [comment]
I think it was like this because `pointertap` isn't defined the [Pointer Events API](https://www.w3.org/TR/pointerevents3/).

**Comment by ShukantPal** [comment]
I would suggest deprecating `pointertap` and making `click` work on touch devices to match the DOM behavior 🤷.

**Comment by bigtimebuddy** [comment]
For now, I'd like to try to match to interaction manager to make the transition easier for folks. Normalizing around pointers makes sense now as it is less breaking and internally consistent.

However, I'd like to introduce a breaking change later on to make events as close to the DOM as possible, which was always the intention anyways. Any convenience (pointertap) or normalization (default pointers) should be built on-top of events. I think we can explore this more in v7.

**Pull request merged**
