### PR TITLE
Fixed plugins duplicating

### PR DESCRIPTION
**Pull request by saitonakamura**
##### Description of change

During the https://github.com/pixijs/pixijs/commit/84096a7d4c82522a62ecf354f459d89277f8b903, an important details was lost, namely checking for duplicate plugins https://github.com/pixijs/pixijs/commit/84096a7d4c82522a62ecf354f459d89277f8b903#diff-975c951909dd96296e87b4491bef8dcd42606b9174e880e3ce30e92120b911afL195

##### Pre-Merge Checklist

- [x] Tests and/or benchmarks are included
- [ ] Documentation is changed or added
- [x] Lint process passed (`npm run lint`)
- [x] Tests passed (`npm run test`)

### CODE REVIEW

**Comment by bigtimebuddy** [comment]
Thanks for spotting this. Do you think you can make a test that reproduces the duplication error?

**Comment by saitonakamura** [comment]
Yeah, working on this

**Comment by saitonakamura** [comment]
Do I need to do anything else, like rebase or squash it?

**Review by bigtimebuddy — APPROVED** [review]
You're good, thank you!

**Pull request merged**
