### PR TITLE
Fix crash creating cached bitmap when filters is empty array

### PR DESCRIPTION
**Pull request by qwertywelch**
##### Description of change

In initCachedDisplayObject, it adds padding from the first filter applied to the DisplayObject if the filters property is truthy, meaning it would attempt to do so even if filters was an empty array. This change checks that's not an empty array, preventing a crash in such a scenario.

##### Pre-Merge Checklist

- [x] Tests and/or benchmarks are included
- [x] Lint process passed (`npm run lint`)
- [x] Tests passed (`npm run test`)

### CODE REVIEW

**Comment by bigtimebuddy** [comment]
Would it be possible to add a test for this situation?

**Comment by qwertywelch** [comment]
Test added!

**Review by bigtimebuddy — APPROVED** [review]
Awesome, thanks for the fix!

**Review by Zyie — APPROVED** [review]

**Comment by bigtimebuddy** [comment]
Thanks @qwertywelch!

**Pull request merged**
