### PR TITLE
Fix attribute location

### PR DESCRIPTION
**Pull request by dev7355608**
##### Description of change

Not sure why the attribute location are manually bound instead of using the locations the compiler/linker chose (`getAttribLocation`). Shaders with layout location specifiers do not work because of this (layout location specifiers cannot be overridden): https://www.pixiplayground.com/#/edit/GleYmYB2SrVtbDyw5Tlhv.

##### Pre-Merge Checklist

- [ ] Tests and/or benchmarks are included
- [x] Lint process passed (`npm run lint`)
- [x] Tests passed (`npm run test`)

### CODE REVIEW

**Review by ShukantPal — APPROVED** [review]
LGTM. This may have some side effects we can't see right now.

**Review by ivanpopelyshev — APPROVED** [review]
Wait, we didnt have `getAttribLocation` in pixi core, at all?

**Comment by ivanpopelyshev** [comment]
Yes, agree, we need this for specifiers. btw in WebGPU they are specified in shader, always.

**Comment by GoodBoyDigital** [comment]
Just throwing this out there.. but would be good to understand what the use cases for manually setting the locations might be?

**Comment by dev7355608** [comment]
> Just throwing this out there.. but would be good to understand what the use cases for manually setting the locations might be?

We can force the locations to a specific layout and make sure two different shaders work with the same VAO. But this only works at the moment if both shaders use the same attributes. If one uses just a subset, pixi creates two different VAOs, but one of those VAOs could be used for both shaders. But pixi doesn't detect that at the moment.

```glsl
layout(location = 0) in vec2 aAttribute1;
layout(location = 1) in vec3 aAttribute2;
```
```glsl
layout(location = 1) in vec3 aAttribute2;
```

If pixi detected that, this could solve multiple VAO problem mentioned here, though it requires the user to setup the locations correctly themselves, but this is very easy to do. Automatically modifying the locations at run time is probably a very messy.
https://github.com/pixijs/pixijs/blob/cf828cf40c36a6d8cd2af7c4a79287238f3437b9/packages/core/src/geometry/GeometrySystem.ts#L160-L164

**Comment by dev7355608** [comment]
Attributes locations of GLSL 1.00 programs now bound by pixi again (as before) to guarantee the same location layout for shaders with the same active attributes. So this change affects only GLSL 3.00 programs now.

**Review by GoodBoyDigital — APPROVED** [review]
nice, yeah I like that this only affects GLSL 3.00!

**Comment by bigtimebuddy** [comment]
Thanks @dev7355608

**Pull request merged**
