### PR TITLE
Split asset parsers into individual packages

### PR DESCRIPTION
**Pull request by Zyie**
This PR splits all the parsers into individual packages e.g text-bitmap, spritesheet, basis, compressed-textures

I also added `@pixi/assets` to the main bundle and deleted `@pixi/loader`

### CODE REVIEW

**Comment by Zyie** [comment]
The failing test has just revealed a bug with the bitmap loader. It doesn't parse a split fonts pages in the correct order all the time

Working on a fix for that now

**Comment by bigtimebuddy** [comment]
Even when it did pass, there's an issue with [webdoc](https://github.com/pixijs/pixijs/runs/8023507066?check_suite_focus=true#step:11:843). This seems new.

**Comment by bigtimebuddy** [comment]
Otherwise, I'm so excited for this PR!

**Comment by Zyie** [comment]
> Even when it did pass, there's an issue with [webdoc](https://github.com/pixijs/pixijs/runs/8023507066?check_suite_focus=true#step:11:843). This seems new.

ah, will also look into this as well

**Comment by Zyie** [comment]
@bigtimebuddy all fixed

**Pull request merged**
