### PR TITLE
Add crossOrigin with credentials support for XHR requests (#7947)

### PR DESCRIPTION
**Pull request by sergaks**
##### Description of change
Add crossOrigin with credentials support for XHR requests when crossOrigion option equals 'use-credentials'

##### Pre-Merge Checklist

- [ ] Tests and/or benchmarks are included
- [ ] Documentation is changed or added
- [x] Lint process passed (`npm run lint`)
- [x] Tests passed (`npm run test`)

### CODE REVIEW

**Comment by bigtimebuddy** [comment]
Thanks for the PR. Is there anyway to unit-test this?

**Comment by sergaks** [comment]
I've added unit test for this, but there is typo in unit test file name that prevents it to run as part of regular test flow: 
packages/loaders/test/LoaderResource.test.ts - must be LoaderResource.tests.ts
After renaming the file, there are multiple test failures in existing tests, because there are were not run before.
Should the issue with tests addressed in dedicated PR?

**Review by Pi-Bouf — APPROVED** [review]

**Comment by bigtimebuddy** [comment]
I created a new issue #7949 for the test failures, thanks for finding this issue.

**Review by bigtimebuddy — APPROVED** [review]

**Review by GoodBoyDigital — APPROVED** [review]
👍

**Comment by bigtimebuddy** [comment]
Thanks @sergaks!

**Pull request merged**
