### PR TITLE
Fix round line join

### LINKED ISSUE #8288: Line cap/join not applied when line segments are drawn in opposite direction
### Expected Behavior
it should render a line cap if a line turns by 180°
### Current Behavior
it just hacks off the end as if no cap or join were used
### Steps to Reproduce
1. Draw a line between any points using lineTo or any other function like the bezier ones
2. Draw a line goin the other direction from the end point of that line, turning by exactly 180°

Example code:
```typescript
const g = new PIXI.Graphics();

g.lineStyle({
  width: 50,
  color: 0xffffff,
  cap: PIXI.LINE_CAP.ROUND,
  join: PIXI.LINE_JOIN.ROUND
});

g.moveTo(200, 200);
g.lineTo(200, 300);
g.lineTo(200, 200);
```

### Environment

- **`pixi.js` version**: 6.3.0
- **Browser & Version**: Chrome 100
- **OS & Version**: Windows 10
- **Running Example**: https://codesandbox.io/s/pixiexample-forked-cvqi44

### PR DESCRIPTION
**Pull request by dev7355608**
##### Description of change

Fixes #8288.

Before: https://www.pixiplayground.com/#/edit/tbwiR5jHfNTXTF-E_d2AF
After: https://www.pixiplayground.com/#/edit/vT8SdivEYyzo-MH3zE1PX

##### Pre-Merge Checklist

- [x] Lint process passed (`npm run lint`)
- [x] Tests passed (`npm run test`)

### CODE REVIEW

**Review by bigtimebuddy — APPROVED** [review]
Wow, great work @dev7355608

**Comment by bencresty** [comment]
@dev7355608 Thanks a lot for this! Looks great!

**Comment by mmmintdesign** [comment]
This bug also happens with bezierCurveTo

https://www.pixiplayground.com/#/edit/mr1KrSdvWUI5WR7Pk1luL

**Comment by bigtimebuddy** [comment]
@mmmintdesign could you file a new issue and link to this?

**Pull request merged**
