### PR TITLE
Add strict null checks to @pixijs/runner

### PR DESCRIPTION
**Pull request by 8times12**
##### Description of change

Ref https://github.com/pixijs/pixijs/issues/8852

To resolve the strict null check error in `packages/runner/src/Runner.ts`, I modified the `destroy` method to set each property value from null to an empty array or an empty string.

I also considered making each property nullable, but decided not to change the type for the following reasons:

- If I make each property nullable, it would require implementing null check processing in the calling code, leading to broader implications.
- There is currently no handling in the calling code to anticipate cases where the property value might be null.

##### Pre-Merge Checklist

- [x] Tests and/or benchmarks are included
- [x] Documentation is changed or added
- [x] Lint process passed (`npm run lint`)
- [x] Tests passed (`npm run test`)

### CODE REVIEW

**Comment by 8times12** [comment]
Another approach could be setting a `destroyed` flag when calling the `destroy` method, and throwing errors whenever methods are invoked while this flag is set.
While this might be more appropriate for the post-destroy logic, considering design consistency, similar adjustments would be needed for other classes that implement the `destroy` method.

**Review by bigtimebuddy — APPROVED** [review]
This effort went stale for awhile, thanks for bring back strict null checks! :tada:

**Comment by 8times12** [comment]
@bigtimebuddy 
Thank you for the review!
I have made the necessary corrections based on your suggestions. Please review it again.

**Comment by bigtimebuddy** [comment]
Thanks @8times12

**Pull request merged**
