### PR TITLE
Fix radius documentation for `PIXI.Circle`

### PR DESCRIPTION
**Pull request by ceoshikhar**
##### Description of change

Fixed the documentation for radius member of `PIXI.Circle`. It said the default value of `radius` is `1` but it is actually `0`. If it's the other way round, that the documentation is correct and the default value is supposed to be `1` instead of `0` then I can make that change in a different PR.

##### Pre-Merge Checklist

- [ ] Tests and/or benchmarks are included
- [x] Documentation is changed or added
- [ ] Lint process passed (`npm run lint`)
- [ ] Tests passed (`npm run test`)

### CODE REVIEW

**Review by bigtimebuddy — CHANGES_REQUESTED** [review]
This seems incorrect. The constructor's default value for radius is `0` not `1`. Where did 1 come from, unless I'm missing something?

**Comment by ceoshikhar** [comment]
You are correct, the default radius is `0` but the code documentation says `1` and even the [circle documentation](https://pixijs.download/release/docs/PIXI.Circle.html) says the default value for radius is `1`. The intent of this PR is to fix the documentation and change default value of radius from `1` to `0`.

**Review by bigtimebuddy — APPROVED** [review]
Oops, you're right. I read this backwards! Good fix, thanks @ceoshikhar

**Review by GoodBoyDigital — APPROVED** [review]

**Comment by bigtimebuddy** [comment]
Thanks @ceoshikhar

**Pull request merged**
