### PR TITLE
Favor Discord for PixiJS community chat

### PR DESCRIPTION
**Pull request by bigtimebuddy**
We have decided to shift our online community focus to Discord away from Slack and Gitter.

### CODE REVIEW

**Review by GoodBoyDigital — APPROVED** [review]
lgtm!

**Comment by bigtimebuddy** [comment]
Slight change of plans... with the help of @miltoncandelero, we have decided to refocus the WebGL & WebGPU Discord community to have a stronger emphasis on PixiJS. There's already and active Pixi base there and it makes sense to combine forces.

**Review by andrewstart — APPROVED** [review]

**Comment by ivanpopelyshev** [comment]
Conviniently, I happened to be owner of server, so i was able to make @miltoncandelero new owner :)

**Comment by epaezrubio** [comment]
The Discord invite link seems to be broken though 😟

**Pull request merged**
