### PR TITLE
Fixes drop shadow positioning with resolutions other than 1

### PR DESCRIPTION
**Pull request by themoonrat**
##### Description of change
Fixed issue with visuals of drop shadows on different renderer / text resolutions
https://github.com/pixijs/pixijs/issues/8004

Text Before Fix: https://jsfiddle.net/vsu1ermb/1/
Text After Fix: https://jsfiddle.net/3v1Lb54e/2/
Bitmap Font Before Fix: https://jsfiddle.net/o2ryepz0/
Bitmap Font After Fix: https://jsfiddle.net/47gLmkc1/1/

##### Pre-Merge Checklist
- [x] Lint process passed (`npm run lint`)
- [x] Tests passed (`npm run test`)

### CODE REVIEW

**Review by bigtimebuddy — APPROVED** [review]
Checks out:

Before (dev branch):
https://jsfiddle.net/bigtimebuddy/d9n0rc4b/

After (this PR):
https://jsfiddle.net/bigtimebuddy/h2ngek8m/

**Review by GoodBoyDigital — APPROVED** [review]
nice! 👍

**Comment by bigtimebuddy** [comment]
Thanks @themoonrat

**Comment by goldenratio** [comment]
can this be cherry picked to v5? Can I do the PR?

**Comment by bigtimebuddy** [comment]
@goldenratio yeah go for it. Please make this to v5.3.x branch

**Comment by goldenratio** [comment]
> @goldenratio yeah go for it. Please make this to v5.3.x branch

@bigtimebuddy  https://github.com/pixijs/pixijs/pull/8218

**Pull request merged**
